# 1. Create a null vector of size 10 but the fifth value which is 1.

In [34]:
import numpy as np

In [35]:
# create null vector of size 10
vector = np.zeros(10)

In [36]:
print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [37]:
# set the fifth value to 1
vector[4] = 1

In [39]:
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# 2. Create a vector with values ranging from 10 to 49.

In [40]:
arr = np.arange(10,50)

In [42]:
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# 3. Create a 3x3 matrix with values ranging from 0 to 8.

In [44]:
arr1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [45]:
arr1.shape 

(9,)

In [47]:
arr1 = arr1.reshape(3,3)

In [48]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# 4. Find indices of non-zero elements from [1,2,0,0,4,0].

In [50]:
arr2 = np.array([1,2,0,0,4,0])

In [51]:
arr2

array([1, 2, 0, 0, 4, 0])

In [52]:
arr3 = np.nonzero(arr2)

In [54]:
print(arr3)

(array([0, 1, 4], dtype=int64),)


# 5. Create a 10x10 array with random values and find the minimum and maximum values.

In [79]:
arr4 = np.random.randint(1,100,(10,10))

In [80]:
arr4

array([[99,  6, 85, 60, 90, 84, 10, 89, 59, 49],
       [22, 54, 61, 79, 36, 79,  2, 64, 94, 61],
       [17, 39, 59, 46,  8, 69, 83, 24, 52, 63],
       [56, 86, 74, 21, 87, 86, 36, 83,  8, 61],
       [45, 35, 29, 67, 37, 80, 10, 57, 71, 36],
       [ 4, 98, 90, 27, 54, 21,  2, 49,  3, 86],
       [12, 29,  1, 40, 75,  7, 92, 69, 27, 41],
       [95, 98, 92, 28, 51, 81, 35,  7, 70, 64],
       [44, 35, 77, 46, 66, 54, 84, 36, 92, 99],
       [73, 38, 14, 70, 55,  5, 99, 75, 93, 82]])

In [81]:
arr4.min()

1

In [82]:
arr4.max()

99

# 6. Create a random vector of size 30 and find the mean value.

In [83]:
arr5 = np.random.random(30)

In [84]:
arr5

array([0.97019435, 0.56762548, 0.59900413, 0.41749541, 0.75523089,
       0.6499699 , 0.5712696 , 0.4341346 , 0.82377567, 0.5510884 ,
       0.55911994, 0.18872567, 0.54703591, 0.0436595 , 0.26215747,
       0.85409151, 0.81902103, 0.91486986, 0.96780088, 0.49199822,
       0.39200802, 0.65255711, 0.91066048, 0.60620719, 0.23160222,
       0.96684541, 0.00209477, 0.98943056, 0.99908056, 0.87349353])

In [85]:
print(arr5.mean())

0.6204082760422905
